stages:
  - name: extract_files
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        output_folder_PU: '{workdir}/PU'
        output_folder_noPU: '{workdir}/noPU'
      step:
        process:
          process_type: interpolated-script-cmd
          interpreter: bash
          script: |
            for i in $(ls {output_folder_PU}); do
              tar -xvzf {output_folder_PU}/$i -C {output_folder_PU}
            done

            for i in $(ls {output_folder_noPU}); do
              tar -xvzf {output_folder_noPU}$i -C {output_folder_noPU}
            done
        publisher:
          publisher_type: 'frompar-pub'
          outputmap:
            outputfile: '{output_folder}'
        environment:
          environment_type: 'docker-encapsulated'
          image: alintulu/jec
          imagetag: cc7-reana-v4-files