stages:
  - name: produce_ntuple
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file_PU: ["/home/cmsusr/input/JRA235.root", "/home/cmsusr/input/JRA173.root"] 
        input_file_noPU: ["/home/cmsusr/input/JRA109.root", "/home/cmsusr/input/JRA72.root", "/home/cmsusr/input/JRA86.root"]
        algo: 'ak4pfchs'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
      workflow: {$ref: workflow_ntuple.yaml}

  - name: match_lumi
    dependencies: [produce_ntuple]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        lumi_file_PU: {stages: 'produce_ntuple[*].list_lumi_PU', output: lumi_file}
        lumi_file_noPU: {stages: 'produce_ntuple[*].list_lumi_noPU', output: lumi_file}
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_file: '{workdir}/Matchedfiles.yml'
      step: {$ref: steps.yaml#/match_lumi}
        
  - name: match_jets
    dependencies: [match_lumi]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        input_file: {stages: 'match_lumi', output: MatchedFiles, unwrap: true}
        PU_dist_data: '/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/PileupHistogram-goldenJSON-13tev-2018-69200ub.root'
        mix_conf_mc: '2018_25ns_UltraLegacy_PoissonOOTPU'
        PU_dist_mc: '{workdir}/PU_dist_mc.root'
        algo1: 'ak4pfchs'
        algo2: 'ak4pfchs'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_path: '{workdir}'
        output_file: '{workdir}/output_ak4pfchs.root'
      scatter:
        method: zip
        parameters: [input_file]
      step: {$ref: steps.yaml#/match_jets}

  - name: compute_l1
    dependencies: [match_jets]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: 'match_jets', output: matched_file}
        algo1: 'ak4pfchs'
        algo2: 'ak4pfchs'
        era: 'ParallelMCPreDeriveL1'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_path: '{workdir}'
        output_file: '{workdir}/ParallelMC_L1FastJet_AK4PFCHS.txt'
      step: {$ref: steps.yaml#/compute_l1}

  - name: higher_level
    dependencies: [compute_l1]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        l1_corr: {stages: 'compute_l1', output: l1_corr}
        algs: 'ak4pfchs'
        input_file: ["/home/cmsusr/input/JRA235.root", "/home/cmsusr/input/JRA173.root"]
        PU_dist_data: '/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/PileupHistogram-goldenJSON-13tev-2018-69200ub.root'
        PU_dist_mc: {stages: 'match_jets', output: PU_dist_mc}
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
      batchsize: 2
      scatter:
        method: zip
        parameters: [input_file]
      workflow: {$ref: workflow_higher_level.yaml}

  - name: compute_l2l3
    dependencies: [higher_level]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: 'higher_level.[*].histogram', output: histo}
        algs: 'ak4pfchs'
        algsCAP: 'AK4PFCHS'
        era: 'ParallelMC'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_path: '{workdir}'
        output_file: '{workdir}/ParallelMC_L2Relative_AK4PFCHS.txt'
      step: {$ref: 'steps.yaml#/compute_l2l3'}

  - name: closure
    dependencies: [compute_l2l3]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        l1_corr: {stages: 'compute_l1', output: l1_corr}
        l2l3_corr: {stages: 'compute_l2l3', output: l2l3_corr}
        input_file: ["/home/cmsusr/input/JRA235.root", "/home/cmsusr/input/JRA173.root"]
        algs: 'ak4pfchs'
        era: 'ParallelMC'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        PU_dist_data: '/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/PileupHistogram-goldenJSON-13tev-2018-69200ub.root'
        PU_dist_mc: {stages: 'match_jets', output: PU_dist_mc}
        output_path: '{workdir}'
        output_file: '{workdir}/Closure_ak4pfchs.root'
      batchsize: 2
      scatter:
        method: zip
        parameters: [input_file]
      step: {$ref: 'steps.yaml#/closure'}

  - name: plots_closure
    dependencies: [closure]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: 'closure', output: closure}
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_path: '{workdir}'
        output_file: '{workdir}/Closure_ak4pfchs.root'
      step: {$ref: 'steps.yaml#/plot_closure'}