stages:
  - name: temp
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        output_file: '{workdir}/PU_files.yml'
      step: {$ref: steps.yaml#/temp}

  - name: produce_ntuple
    dependencies: [temp]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file_PU: {stages: 'temp', output: PU_files, unwrap: true}
        input_file_noPU: ["/eos/user/a/adlintul/JRA2019/noPU/JRA0.root","/eos/user/a/adlintul/JRA2019/noPU/JRA100.root","/eos/user/a/adlintul/JRA2019/noPU/JRA101.root","/eos/user/a/adlintul/JRA2019/noPU/JRA102.root","/eos/user/a/adlintul/JRA2019/noPU/JRA103.root","/eos/user/a/adlintul/JRA2019/noPU/JRA104.root","/eos/user/a/adlintul/JRA2019/noPU/JRA105.root","/eos/user/a/adlintul/JRA2019/noPU/JRA106.root","/eos/user/a/adlintul/JRA2019/noPU/JRA107.root","/eos/user/a/adlintul/JRA2019/noPU/JRA108.root","/eos/user/a/adlintul/JRA2019/noPU/JRA109.root","/eos/user/a/adlintul/JRA2019/noPU/JRA10.root","/eos/user/a/adlintul/JRA2019/noPU/JRA110.root","/eos/user/a/adlintul/JRA2019/noPU/JRA111.root","/eos/user/a/adlintul/JRA2019/noPU/JRA112.root","/eos/user/a/adlintul/JRA2019/noPU/JRA113.root","/eos/user/a/adlintul/JRA2019/noPU/JRA114.root","/eos/user/a/adlintul/JRA2019/noPU/JRA115.root","/eos/user/a/adlintul/JRA2019/noPU/JRA116.root","/eos/user/a/adlintul/JRA2019/noPU/JRA117.root","/eos/user/a/adlintul/JRA2019/noPU/JRA118.root","/eos/user/a/adlintul/JRA2019/noPU/JRA119.root","/eos/user/a/adlintul/JRA2019/noPU/JRA11.root","/eos/user/a/adlintul/JRA2019/noPU/JRA120.root","/eos/user/a/adlintul/JRA2019/noPU/JRA121.root","/eos/user/a/adlintul/JRA2019/noPU/JRA122.root","/eos/user/a/adlintul/JRA2019/noPU/JRA123.root","/eos/user/a/adlintul/JRA2019/noPU/JRA124.root","/eos/user/a/adlintul/JRA2019/noPU/JRA125.root","/eos/user/a/adlintul/JRA2019/noPU/JRA126.root","/eos/user/a/adlintul/JRA2019/noPU/JRA127.root","/eos/user/a/adlintul/JRA2019/noPU/JRA128.root","/eos/user/a/adlintul/JRA2019/noPU/JRA129.root","/eos/user/a/adlintul/JRA2019/noPU/JRA12.root","/eos/user/a/adlintul/JRA2019/noPU/JRA130.root","/eos/user/a/adlintul/JRA2019/noPU/JRA131.root","/eos/user/a/adlintul/JRA2019/noPU/JRA132.root","/eos/user/a/adlintul/JRA2019/noPU/JRA133.root","/eos/user/a/adlintul/JRA2019/noPU/JRA134.root","/eos/user/a/adlintul/JRA2019/noPU/JRA135.root","/eos/user/a/adlintul/JRA2019/noPU/JRA136.root","/eos/user/a/adlintul/JRA2019/noPU/JRA137.root","/eos/user/a/adlintul/JRA2019/noPU/JRA138.root","/eos/user/a/adlintul/JRA2019/noPU/JRA13.root","/eos/user/a/adlintul/JRA2019/noPU/JRA14.root","/eos/user/a/adlintul/JRA2019/noPU/JRA15.root","/eos/user/a/adlintul/JRA2019/noPU/JRA16.root","/eos/user/a/adlintul/JRA2019/noPU/JRA17.root","/eos/user/a/adlintul/JRA2019/noPU/JRA18.root","/eos/user/a/adlintul/JRA2019/noPU/JRA19.root","/eos/user/a/adlintul/JRA2019/noPU/JRA1.root","/eos/user/a/adlintul/JRA2019/noPU/JRA20.root","/eos/user/a/adlintul/JRA2019/noPU/JRA21.root","/eos/user/a/adlintul/JRA2019/noPU/JRA22.root","/eos/user/a/adlintul/JRA2019/noPU/JRA23.root","/eos/user/a/adlintul/JRA2019/noPU/JRA24.root","/eos/user/a/adlintul/JRA2019/noPU/JRA25.root","/eos/user/a/adlintul/JRA2019/noPU/JRA26.root","/eos/user/a/adlintul/JRA2019/noPU/JRA27.root","/eos/user/a/adlintul/JRA2019/noPU/JRA28.root","/eos/user/a/adlintul/JRA2019/noPU/JRA29.root","/eos/user/a/adlintul/JRA2019/noPU/JRA2.root","/eos/user/a/adlintul/JRA2019/noPU/JRA30.root","/eos/user/a/adlintul/JRA2019/noPU/JRA31.root","/eos/user/a/adlintul/JRA2019/noPU/JRA32.root","/eos/user/a/adlintul/JRA2019/noPU/JRA33.root","/eos/user/a/adlintul/JRA2019/noPU/JRA34.root","/eos/user/a/adlintul/JRA2019/noPU/JRA35.root","/eos/user/a/adlintul/JRA2019/noPU/JRA36.root","/eos/user/a/adlintul/JRA2019/noPU/JRA37.root","/eos/user/a/adlintul/JRA2019/noPU/JRA38.root","/eos/user/a/adlintul/JRA2019/noPU/JRA39.root","/eos/user/a/adlintul/JRA2019/noPU/JRA3.root","/eos/user/a/adlintul/JRA2019/noPU/JRA40.root","/eos/user/a/adlintul/JRA2019/noPU/JRA41.root","/eos/user/a/adlintul/JRA2019/noPU/JRA42.root","/eos/user/a/adlintul/JRA2019/noPU/JRA43.root","/eos/user/a/adlintul/JRA2019/noPU/JRA44.root","/eos/user/a/adlintul/JRA2019/noPU/JRA45.root","/eos/user/a/adlintul/JRA2019/noPU/JRA46.root","/eos/user/a/adlintul/JRA2019/noPU/JRA47.root","/eos/user/a/adlintul/JRA2019/noPU/JRA48.root","/eos/user/a/adlintul/JRA2019/noPU/JRA49.root","/eos/user/a/adlintul/JRA2019/noPU/JRA4.root","/eos/user/a/adlintul/JRA2019/noPU/JRA50.root","/eos/user/a/adlintul/JRA2019/noPU/JRA51.root","/eos/user/a/adlintul/JRA2019/noPU/JRA52.root","/eos/user/a/adlintul/JRA2019/noPU/JRA53.root","/eos/user/a/adlintul/JRA2019/noPU/JRA54.root","/eos/user/a/adlintul/JRA2019/noPU/JRA55.root","/eos/user/a/adlintul/JRA2019/noPU/JRA56.root","/eos/user/a/adlintul/JRA2019/noPU/JRA57.root","/eos/user/a/adlintul/JRA2019/noPU/JRA58.root","/eos/user/a/adlintul/JRA2019/noPU/JRA59.root","/eos/user/a/adlintul/JRA2019/noPU/JRA5.root","/eos/user/a/adlintul/JRA2019/noPU/JRA60.root","/eos/user/a/adlintul/JRA2019/noPU/JRA61.root","/eos/user/a/adlintul/JRA2019/noPU/JRA62.root","/eos/user/a/adlintul/JRA2019/noPU/JRA63.root","/eos/user/a/adlintul/JRA2019/noPU/JRA64.root","/eos/user/a/adlintul/JRA2019/noPU/JRA65.root","/eos/user/a/adlintul/JRA2019/noPU/JRA66.root","/eos/user/a/adlintul/JRA2019/noPU/JRA67.root","/eos/user/a/adlintul/JRA2019/noPU/JRA68.root","/eos/user/a/adlintul/JRA2019/noPU/JRA69.root","/eos/user/a/adlintul/JRA2019/noPU/JRA6.root","/eos/user/a/adlintul/JRA2019/noPU/JRA70.root","/eos/user/a/adlintul/JRA2019/noPU/JRA71.root","/eos/user/a/adlintul/JRA2019/noPU/JRA72.root","/eos/user/a/adlintul/JRA2019/noPU/JRA73.root","/eos/user/a/adlintul/JRA2019/noPU/JRA74.root","/eos/user/a/adlintul/JRA2019/noPU/JRA75.root","/eos/user/a/adlintul/JRA2019/noPU/JRA76.root","/eos/user/a/adlintul/JRA2019/noPU/JRA77.root","/eos/user/a/adlintul/JRA2019/noPU/JRA78.root","/eos/user/a/adlintul/JRA2019/noPU/JRA79.root","/eos/user/a/adlintul/JRA2019/noPU/JRA7.root","/eos/user/a/adlintul/JRA2019/noPU/JRA80.root","/eos/user/a/adlintul/JRA2019/noPU/JRA81.root","/eos/user/a/adlintul/JRA2019/noPU/JRA82.root","/eos/user/a/adlintul/JRA2019/noPU/JRA83.root","/eos/user/a/adlintul/JRA2019/noPU/JRA84.root","/eos/user/a/adlintul/JRA2019/noPU/JRA85.root","/eos/user/a/adlintul/JRA2019/noPU/JRA86.root","/eos/user/a/adlintul/JRA2019/noPU/JRA87.root","/eos/user/a/adlintul/JRA2019/noPU/JRA88.root","/eos/user/a/adlintul/JRA2019/noPU/JRA89.root","/eos/user/a/adlintul/JRA2019/noPU/JRA8.root","/eos/user/a/adlintul/JRA2019/noPU/JRA90.root","/eos/user/a/adlintul/JRA2019/noPU/JRA91.root","/eos/user/a/adlintul/JRA2019/noPU/JRA92.root","/eos/user/a/adlintul/JRA2019/noPU/JRA93.root","/eos/user/a/adlintul/JRA2019/noPU/JRA94.root","/eos/user/a/adlintul/JRA2019/noPU/JRA95.root","/eos/user/a/adlintul/JRA2019/noPU/JRA96.root","/eos/user/a/adlintul/JRA2019/noPU/JRA97.root","/eos/user/a/adlintul/JRA2019/noPU/JRA98.root","/eos/user/a/adlintul/JRA2019/noPU/JRA99.root","/eos/user/a/adlintul/JRA2019/noPU/JRA9.root"]
        algo: 'AK'
        cone_size: '4'
        jet_type: 'PFchs'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
      workflow: {$ref: workflow_ntuple.yaml}

  - name: match_lumi
    dependencies: [produce_ntuple]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        lumi_file_PU: {stages: 'produce_ntuple[*].list_lumi_PU', output: lumi_file}
        lumi_file_noPU: {stages: 'produce_ntuple[*].list_lumi_noPU', output: lumi_file}
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_file: '{workdir}/Matchedfiles.yml'
      step: {$ref: steps.yaml#/match_lumi}
        
  - name: match_jets
    dependencies: [match_lumi]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        input_file: {stages: 'match_lumi', output: MatchedFiles, unwrap: true}
        PU_dist_data: '/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/PileupHistogram-goldenJSON-13tev-2018-69200ub.root'
        mix_conf_mc: '2018_25ns_UltraLegacy_PoissonOOTPU'
        PU_dist_mc: '{workdir}/PU_dist_mc.root'
        algo: 'AK'
        cone_size: '4'
        jet_type: 'PFchs'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_path: '{workdir}'
        output_file: '{workdir}/output_ak4pfchs.root'
      scatter:
        method: zip
        parameters: [input_file]
      step: {$ref: steps.yaml#/match_jets}

  - name: compute_l1
    dependencies: [match_jets]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: 'match_jets', output: matched_file}
        algo: 'AK'
        cone_size: '4'
        jet_type: 'PFchs'
        era: 'ParallelMC'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_path: '{workdir}'
        output_file: '{workdir}/ParallelMC_L1FastJet_AK4PFchs.txt'
      step: {$ref: steps.yaml#/compute_l1}

  - name: higher_level
    dependencies: [compute_l1]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        l1_corr: {stages: 'compute_l1', output: l1_corr}
        algo: 'AK'
        cone_size: '4'
        jet_type: 'PFchs'
        input_file: {stages: 'temp', output: PU_files, unwrap: true}
        PU_dist_data: '/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/PileupHistogram-goldenJSON-13tev-2018-69200ub.root'
        PU_dist_mc: {stages: 'match_jets', output: PU_dist_mc}
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
      batchsize: 20
      scatter:
        method: zip
        parameters: [input_file]
      workflow: {$ref: workflow_higher_level.yaml}

  - name: compute_l2l3
    dependencies: [higher_level]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: 'higher_level.[*].histogram', output: histo}
        algo: 'AK'
        cone_size: '4'
        jet_type: 'PFchs'
        era: 'ParallelMC'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_path: '{workdir}'
        output_file: '{workdir}/ParallelMC_L2Relative_AK4PFchs.txt'
      step: {$ref: 'steps.yaml#/compute_l2l3'}

  - name: closure
    dependencies: [compute_l2l3]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        l1_corr: {stages: 'compute_l1', output: l1_corr}
        l2l3_corr: {stages: 'compute_l2l3', output: l2l3_corr}
        input_file: {stages: 'temp', output: PU_files, unwrap: true}
        algo: 'AK'
        cone_size: '4'
        jet_type: 'PFchs'
        era: 'ParallelMC'
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        PU_dist_data: '/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/PileupHistogram-goldenJSON-13tev-2018-69200ub.root'
        PU_dist_mc: {stages: 'match_jets', output: PU_dist_mc}
        output_path: '{workdir}'
        output_file: '{workdir}/Closure_ak4pfchs.root'
      batchsize: 20
      scatter:
        method: zip
        parameters: [input_file]
      step: {$ref: 'steps.yaml#/closure'}

  - name: plots_closure
    dependencies: [closure]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: 'closure', output: closure}
        release: 'CMSSW_10_6_12'
        scram_arch: 'slc7_amd64_gcc700'
        output_path: '/eos/user/a/adlintul/reana/plot_closure'
        output_file: '{workdir}/Closure_ak4pfchs.root'
      step: {$ref: 'steps.yaml#/plot_closure'}